"""Run every exact checker included in this repository."""

from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = (
    "verification/check_repository_integrity.py",
    "verification/verify_a183068.py",
    "verification/related/verify_arithmetic_frobenius_packet_framework.py",
    "verification/related/verify_landau_supercongruence.py",
    "verification/related/verify_catalan_ballot_supercongruences.py",
    "verification/related/verify_bala_oeis_supercongruences.py",
    "verification/related/verify_a219562_enhanced_tower.py",
    "verification/related/verify_a112028_enhanced_tower.py",
    "verification/related/verify_a375178_enhanced_odd_tower.py",
    "verification/related/verify_a375179_a375180_signed_towers.py",
    "verification/related/verify_bala_110_campaign.py",
    "verification/related/verify_franel_companion_ct_reduction.py",
    "verification/related/verify_balanced_matrix_coefficient_tower.py",
    "verification/related/verify_a244973_frobenius_reduction.py",
    "verification/related/verify_a331562_uniform_rational_diagonal.py",
    "verification/related/verify_a079489_lagrange_kernel.py",
    "verification/related/verify_exponential_coefficient_cartier.py",
    "verification/related/verify_a376_apery_companions.py",
    "verification/related/verify_a376458_enhanced_tower.py",
    "verification/related/verify_a376466_ordinary_tower.py",
    "verification/related/verify_a212334_enhanced_prime.py",
    "verification/related/verify_quadrinomial_coefficient_tower.py",
    "verification/related/verify_mixed_step_coefficient_tower.py",
    "verification/related/verify_a260667_prime_boundary.py",
    "verification/related/verify_apery_odd_moment_prime_classification.py",
    "verification/related/verify_coefficient_framing_cubic_tower.py",
    "verification/related/verify_bala_august_coefficient_packet.py",
    "verification/related/verify_bala_august_mixed_binomial_follow_on.py",
    "verification/related/verify_a333473_algebraic_family_tower.py",
    "verification/related/verify_index_dependent_companion_boundary.py",
    "verification/related/verify_mixed_negative_binomial_cubic_tower.py",
    "verification/related/verify_bala_august_first_defect.py",
    "verification/related/verify_bala_august_kernel_frobenius.py",
    "verification/related/verify_prime_three_negative_binomial_boundary.py",
    "verification/related/verify_rational_framing_counterexample.py",
    "verification/related/verify_straub_prime5_packet.py",
    "verification/related/verify_a108628_half_index.py",
    "verification/related/verify_a365029_first_two_levels.py",
    "verification/related/verify_a365029_all_level_digit_reduction.py",
    "verification/related/verify_binomial_quotient_cancellation.py",
    "verification/related/verify_a288470_odd_prime_tower.py",
    "verification/related/verify_multinomial_power_towers.py",
    "verification/related/verify_a132303_trinomial_cube.py",
    "verification/related/verify_a156554_legendre_tower.py",
    "verification/related/verify_a351858_cyclotomic_boundary.py",
    "verification/related/verify_a263843_reversion_reduction.py",
    "verification/related/verify_odd_unit_block_towers.py",
    "verification/related/verify_dixon_legendre_towers.py",
    "verification/related/verify_a364173_integral_tower.py",
    "verification/related/verify_a364176_affine_landau.py",
    "verification/related/verify_a364183_affine_landau.py",
    "verification/related/verify_bober_half_index_integrality.py",
    "verification/related/verify_bober_denominator_boundary.py",
    "verification/related/verify_coefficient_power_gauss_baseline.py",
    "verification/related/verify_modular_product_prime_packet.py",
    "verification/related/verify_euler_product_cubic_cartier_moments.py",
    "verification/related/verify_a229452_coefficient_root.py",
    "verification/related/verify_a049505_symmetric_plane_partitions.py",
    "verification/related/verify_a008793_cube_plane_partitions.py",
    "verification/related/verify_symmetric_box_plane_partitions.py",
    "verification/related/verify_balanced_factorial_ratio_towers.py",
    "verification/related/verify_rational_gamma_ratio_towers.py",
    "verification/related/verify_bober_sporadic_packet.py",
    "verification/related/verify_apery_rank_one_defect.py",
    "verification/related/verify_q_calculus_supercongruence.py",
    "verification/related/verify_weighted_lift_collision_synthesis.py",
    "verification/related/verify_dwork_period_supercongruence.py",
    "verification/related/verify_finite_field_determinant_bias.py",
    "verification/related/verify_finite_field_pfaffian_bias.py",
    "verification/related/verify_hyperdeterminant_fourier.py",
    "verification/related/verify_hyperdeterminant_entropy.py",
    "verification/related/verify_zhang_four_matrix_counterexample.py",
    "verification/related/verify_jacobian_counterexample_counts.py",
    "verification/related/verify_jacobian_degree_four.py",
    "verification/related/verify_jacobian_degree_five.py",
    "verification/related/verify_jacobian_euler_orbit_bridge.py",
    "verification/related/verify_crystalline_locus_support_bridge.py",
    "verification/related/verify_eta_prime3.py",
    "verification/related/verify_cooper_level11.py",
    "verification/related/verify_dwork_boundaries.py",
    "verification/related/verify_ehrhart_newton_prime_cutoff.py",
    "verification/related/verify_group_ring_gauss_boundary.py",
    "verification/related/verify_gaussian_twists.py",
    "verification/related/verify_bala_gaussian_twist_pilot.py",
    "verification/related/verify_binomial_power_frobenius.py",
    "verification/related/verify_quadratic_gaussian_queue.py",
    "verification/related/verify_cyclotomic_coefficient_pair.py",
    "verification/related/verify_cyclotomic_rational_framing.py",
    "verification/related/verify_euler_product_gaussian_tower.py",
    "verification/related/verify_dyadic_hypercube_defect.py",
    "verification/related/verify_dyadic_hypercube_walsh.py",
    "verification/related/verify_affine_spectrum_hashing.py",
    "verification/related/verify_chowla_dwork_evans_defect.py",
    "verification/related/verify_gaussian_power_sums.py",
    "verification/related/verify_gaussian_wolstenholme.py",
    "verification/related/verify_gaussian_product_isometry.py",
    "verification/related/experiment_gaussian_product_dynamics.py",
    "verification/related/verify_gq2_orientation_lifts.py",
    "verification/related/verify_gq2_appendices.py",
    "verification/related/verify_gq2_finite_abelian_counts.py",
    "verification/related/verify_gq2_dihedral_counts.py",
    "verification/related/verify_gq2_quaternion_counts.py",
    "verification/related/verify_gq2_maximal_cyclic_counts.py",
    "verification/related/verify_lattice_walk_frobenius.py",
    "verification/related/verify_black_noise_chaos_filter.py",
    "verification/related/verify_dyadic_affine_mixed_cohomology.py",
    "verification/related/verify_dyadic_dehn_twist_sampler.py",
    "verification/related/verify_dyadic_dehn_twist_cayley.py",
    "verification/related/verify_dyadic_twist_grammar.py",
    "verification/related/verify_dyadic_dehn_twist_conjugacy.py",
    "verification/related/verify_higher_degree_box_polynomial.py",
    "verification/related/verify_gaussian_erdos_moser.py",
)


def main() -> None:
    for relative in SCRIPTS:
        print(f"\n=== {relative} ===", flush=True)
        subprocess.run(
            [sys.executable, str(ROOT / relative)],
            cwd=ROOT,
            check=True,
        )
    print(f"\nall {len(SCRIPTS)} verification programs passed")


if __name__ == "__main__":
    main()

